CREATE TABLE judge_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_log_id BIGINT,
  kb_ids BIGINT ARRAY NOT NULL,
  query TEXT NOT NULL,

  faithfulness DECIMAL(4,3),
  context_precision DECIMAL(4,3),
  context_recall DECIMAL(4,3),
  answer_relevance DECIMAL(4,3),
  completeness DECIMAL(4,3),
  citation_accuracy DECIMAL(4,3),
  overall_score DECIMAL(4,3),

  judge_model VARCHAR(64) NOT NULL DEFAULT 'deepseek-chat',
  judge_prompt_version VARCHAR(16) NOT NULL DEFAULT 'v1',
  judge_reasoning TEXT,
  judge_raw_response VARCHAR(2048),
  judge_latency_ms INT,
  judge_cost_cny DECIMAL(10,4),

  status VARCHAR(16) NOT NULL DEFAULT 'COMPLETED',
  failure_reason VARCHAR(256),

  source VARCHAR(16) NOT NULL,
  golden_question_id BIGINT,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE judge_metrics_daily (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  kb_id BIGINT,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  sample_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,

  kb_id_norm BIGINT AS (COALESCE(kb_id, -1)),

  faithfulness_p50 DECIMAL(4,3),
  faithfulness_p95 DECIMAL(4,3),
  context_precision_p50 DECIMAL(4,3),
  context_precision_p95 DECIMAL(4,3),
  answer_relevance_p50 DECIMAL(4,3),
  answer_relevance_p95 DECIMAL(4,3),
  overall_p50 DECIMAL(4,3),
  overall_p95 DECIMAL(4,3),
  overall_mean DECIMAL(4,3),
  overall_std DECIMAL(4,3),
  total_cost_cny DECIMAL(10,4) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_judge_metrics_daily_uniq
  ON judge_metrics_daily(date, kb_id_norm, tenant_id);

CREATE TABLE judge_sampling_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type VARCHAR(16) NOT NULL,
  scope_id BIGINT,
  tenant_id VARCHAR(64),
  sample_rate DECIMAL(4,3) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(128),

  scope_id_norm BIGINT AS (COALESCE(scope_id, -1)),
  tenant_id_norm VARCHAR(64) AS (COALESCE(tenant_id, 'global')),

  CONSTRAINT ck_sampling_scope CHECK (scope_type IN ('GLOBAL','KB','TENANT')),
  CONSTRAINT ck_sampling_rate CHECK (sample_rate >= 0.0 AND sample_rate <= 1.0)
);
CREATE UNIQUE INDEX uk_sampling_config_unique
  ON judge_sampling_config(scope_type, scope_id_norm, tenant_id_norm);
