CREATE TABLE knowledge_bases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(1024),
    embedding_model VARCHAR(128),
    chunk_size INTEGER,
    chunk_overlap INTEGER,
    doc_count INTEGER,
    chunk_count INTEGER,
    status VARCHAR(32),
    tenant_id VARCHAR(128),
    owner_user_id BIGINT,
    visibility VARCHAR(32),
    kb_type VARCHAR(32),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE kb_acl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id BIGINT NOT NULL,
    principal_type VARCHAR(32) NOT NULL DEFAULT 'user',
    principal_id VARCHAR(128) NOT NULL DEFAULT '0',
    permission VARCHAR(16) NOT NULL DEFAULT 'read',
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
